/**
 * FlowScript Audit Trail Tests
 *
 * Tests the hash-chained, append-only audit trail system (src/audit.ts)
 * and its integration with Memory (src/memory.ts).
 *
 * Covers:
 * - Hash chain creation + verification
 * - Tamper detection
 * - Canonical JSON serialization (cross-language compatibility)
 * - Rotation (monthly boundary + size-based)
 * - Compression (gzip round-trip)
 * - Manifest creation + update
 * - Cross-file chain continuity
 * - Query by time range, event type, node ID, session ID, adapter
 * - Legacy file compatibility
 * - GENESIS / LEGACY_BRIDGE handling
 * - on_event callback
 * - Retention cleanup
 * - Memory integration (all event types)
 */

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import * as zlib from 'zlib';
import {
  AuditWriter,
  AuditConfig,
  AuditEntry,
  canonicalStringify,
  GENESIS_HASH,
  LEGACY_BRIDGE_HASH,
  SCHEMA_VERSION,
} from '../src/audit';
import { Memory } from '../src/memory';

// ============================================================================
// Helpers
// ============================================================================

function tmpDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'flowscript-audit-'));
}

function memoryPath(dir: string, name: string = 'test_memory.json'): string {
  return path.join(dir, name);
}

// ============================================================================
// Canonical JSON Serialization
// ============================================================================

describe('canonicalStringify', () => {
  test('sorts keys at top level', () => {
    expect(canonicalStringify({ b: 1, a: 2 })).toBe('{"a":2,"b":1}');
  });

  test('sorts keys recursively', () => {
    expect(canonicalStringify({ b: { d: 1, c: 2 }, a: 3 }))
      .toBe('{"a":3,"b":{"c":2,"d":1}}');
  });

  test('handles arrays (no key sorting)', () => {
    expect(canonicalStringify([3, 1, 2])).toBe('[3,1,2]');
  });

  test('handles null', () => {
    expect(canonicalStringify(null)).toBe('null');
  });

  test('handles strings with escapes', () => {
    expect(canonicalStringify('hello "world"')).toBe('"hello \\"world\\""');
  });

  test('handles nested arrays in objects', () => {
    expect(canonicalStringify({ b: [1, 2], a: 'x' }))
      .toBe('{"a":"x","b":[1,2]}');
  });

  test('handles booleans', () => {
    expect(canonicalStringify({ z: true, a: false })).toBe('{"a":false,"z":true}');
  });

  test('compact separators (no whitespace)', () => {
    const result = canonicalStringify({ a: 1 });
    expect(result).not.toContain(' ');
  });

  test('matches Python json.dumps(sort_keys=True, separators=(",",":"))', () => {
    // This is the critical cross-language test
    // Python: json.dumps({"v":1,"seq":0,"event":"test","prev_hash":"sha256:GENESIS"},sort_keys=True,separators=(",",":"))
    // Expected: {"event":"test","prev_hash":"sha256:GENESIS","seq":0,"v":1}
    const obj = { v: 1, seq: 0, event: 'test', prev_hash: 'sha256:GENESIS' };
    expect(canonicalStringify(obj))
      .toBe('{"event":"test","prev_hash":"sha256:GENESIS","seq":0,"v":1}');
  });

  test('handles undefined values in objects', () => {
    // undefined should be treated like null/missing
    expect(canonicalStringify({ a: undefined, b: 1 })).toBe('{"a":null,"b":1}');
  });

  test('escapes non-ASCII to \\uXXXX (matches Python ensure_ascii=True)', () => {
    // Python: json.dumps("café") → '"caf\\u00e9"'
    expect(canonicalStringify('café')).toBe('"caf\\u00e9"');
  });

  test('escapes emoji via surrogate pairs', () => {
    // Python: json.dumps("👍") → '"\\ud83d\\udc4d"'
    expect(canonicalStringify('👍')).toBe('"\\ud83d\\udc4d"');
  });

  test('escapes CJK characters', () => {
    // Python: json.dumps("你好") → '"\\u4f60\\u597d"'
    expect(canonicalStringify('你好')).toBe('"\\u4f60\\u597d"');
  });

  test('handles control characters', () => {
    expect(canonicalStringify('a\tb\nc')).toBe('"a\\tb\\nc"');
    expect(canonicalStringify('a\x00b')).toBe('"a\\u0000b"');
  });

  test('non-ASCII in object keys', () => {
    expect(canonicalStringify({ café: 1 })).toBe('{"caf\\u00e9":1}');
  });
});

// ============================================================================
// Cross-Language Verification (Python fixtures)
// ============================================================================

describe('Cross-language canonical JSON verification', () => {
  // These fixtures were generated by Python's json.dumps(sort_keys=True, separators=(",",":"), ensure_ascii=True)
  // and hashlib.sha256(). If ANY of these tests fail, cross-language chain verification is broken.

  const PYTHON_ENTRY_1 = {
    v: 1, seq: 0, timestamp: '2026-03-21T23:00:00.000Z', event: 'node_create',
    prev_hash: 'sha256:GENESIS', session_id: 'ses_test123',
    data: { node_id: 'tho_abc123', node_type: 'thought', content: 'Use PostgreSQL for sessions', source: 'api' },
    adapter: { framework: 'langgraph', adapter_class: 'LangGraphStore', operation: 'put' },
  };
  const PYTHON_CANONICAL_1 = '{"adapter":{"adapter_class":"LangGraphStore","framework":"langgraph","operation":"put"},"data":{"content":"Use PostgreSQL for sessions","node_id":"tho_abc123","node_type":"thought","source":"api"},"event":"node_create","prev_hash":"sha256:GENESIS","seq":0,"session_id":"ses_test123","timestamp":"2026-03-21T23:00:00.000Z","v":1}';
  const PYTHON_HASH_1 = 'sha256:71f4bdb83da1c056cbb4b3b921e8d268a6927796816df48507d0a529e301c45c';

  // Entry with Unicode content (café, 你好)
  const PYTHON_ENTRY_2 = {
    v: 1, seq: 1, timestamp: '2026-03-21T23:01:00.000Z', event: 'node_create',
    prev_hash: PYTHON_HASH_1, session_id: null,
    data: { node_id: 'tho_def456', node_type: 'thought', content: 'café 你好', source: 'api' },
    adapter: null,
  };
  const PYTHON_CANONICAL_2 = '{"adapter":null,"data":{"content":"caf\\u00e9 \\u4f60\\u597d","node_id":"tho_def456","node_type":"thought","source":"api"},"event":"node_create","prev_hash":"sha256:71f4bdb83da1c056cbb4b3b921e8d268a6927796816df48507d0a529e301c45c","seq":1,"session_id":null,"timestamp":"2026-03-21T23:01:00.000Z","v":1}';
  const PYTHON_HASH_2 = 'sha256:e8524d0926469f983502de3f13b9c0ef9693e818ffa32c1920359d20da163e6b';

  test('TS canonical JSON matches Python output (entry with adapter)', () => {
    expect(canonicalStringify(PYTHON_ENTRY_1)).toBe(PYTHON_CANONICAL_1);
  });

  test('TS hash matches Python hash (entry with adapter)', () => {
    expect(AuditWriter._computeHash(canonicalStringify(PYTHON_ENTRY_1))).toBe(PYTHON_HASH_1);
  });

  test('TS canonical JSON matches Python output (entry with Unicode)', () => {
    expect(canonicalStringify(PYTHON_ENTRY_2)).toBe(PYTHON_CANONICAL_2);
  });

  test('TS hash matches Python hash (entry with Unicode)', () => {
    expect(AuditWriter._computeHash(canonicalStringify(PYTHON_ENTRY_2))).toBe(PYTHON_HASH_2);
  });

  test('TS can verify a Python-generated audit chain', () => {
    // Simulate a 2-entry audit file generated by Python
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'flowscript-xlang-'));
    const auditPath = path.join(dir, 'test.audit.jsonl');
    fs.writeFileSync(auditPath, PYTHON_CANONICAL_1 + '\n' + PYTHON_CANONICAL_2 + '\n', 'utf-8');

    const result = AuditWriter.verify(auditPath);
    expect(result.valid).toBe(true);
    expect(result.totalEntries).toBe(2);
    expect(result.legacyEntries).toBe(0);

    fs.rmSync(dir, { recursive: true, force: true });
  });
});

// ============================================================================
// AuditWriter — Core
// ============================================================================

describe('AuditWriter — Core', () => {
  let dir: string;

  beforeEach(() => { dir = tmpDir(); });
  afterEach(() => { fs.rmSync(dir, { recursive: true, force: true }); });

  test('creates audit file on first write', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp);
    writer.write('test_event', { foo: 'bar' });

    expect(fs.existsSync(writer.activePath)).toBe(true);
    const content = fs.readFileSync(writer.activePath, 'utf-8').trim();
    const entry = JSON.parse(content);
    expect(entry.v).toBe(SCHEMA_VERSION);
    expect(entry.seq).toBe(0);
    expect(entry.event).toBe('test_event');
    expect(entry.data.foo).toBe('bar');
  });

  test('entries have monotonically increasing seq', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp);
    writer.write('e1', {});
    writer.write('e2', {});
    writer.write('e3', {});

    const lines = fs.readFileSync(writer.activePath, 'utf-8').trim().split('\n');
    expect(lines).toHaveLength(3);
    expect(JSON.parse(lines[0]).seq).toBe(0);
    expect(JSON.parse(lines[1]).seq).toBe(1);
    expect(JSON.parse(lines[2]).seq).toBe(2);
  });

  test('entries include session_id when provided', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp);
    writer.write('e1', {}, 'ses_123');

    const entry = JSON.parse(fs.readFileSync(writer.activePath, 'utf-8').trim());
    expect(entry.session_id).toBe('ses_123');
  });

  test('entries include adapter when provided', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp);
    writer.write('e1', {}, null, { framework: 'crewai', adapter_class: 'CrewAIStorage', operation: 'save' });

    const entry = JSON.parse(fs.readFileSync(writer.activePath, 'utf-8').trim());
    expect(entry.adapter).toEqual({ framework: 'crewai', adapter_class: 'CrewAIStorage', operation: 'save' });
  });

  test('session_id defaults to null', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp);
    writer.write('e1', {});

    const entry = JSON.parse(fs.readFileSync(writer.activePath, 'utf-8').trim());
    expect(entry.session_id).toBeNull();
  });

  test('adapter defaults to null', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp);
    writer.write('e1', {});

    const entry = JSON.parse(fs.readFileSync(writer.activePath, 'utf-8').trim());
    expect(entry.adapter).toBeNull();
  });

  test('write returns the entry dict', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp);
    const entry = writer.write('test', { x: 1 });

    expect(entry.v).toBe(1);
    expect(entry.event).toBe('test');
    expect(entry.data.x).toBe(1);
  });
});

// ============================================================================
// Hash Chain
// ============================================================================

describe('AuditWriter — Hash Chain', () => {
  let dir: string;

  beforeEach(() => { dir = tmpDir(); });
  afterEach(() => { fs.rmSync(dir, { recursive: true, force: true }); });

  test('first entry has GENESIS prev_hash', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp);
    writer.write('e1', {});

    const entry = JSON.parse(fs.readFileSync(writer.activePath, 'utf-8').trim());
    expect(entry.prev_hash).toBe(GENESIS_HASH);
  });

  test('second entry chains from first', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp);
    writer.write('e1', {});
    writer.write('e2', {});

    const lines = fs.readFileSync(writer.activePath, 'utf-8').trim().split('\n');
    const e1 = JSON.parse(lines[0]);
    const e2 = JSON.parse(lines[1]);

    // e2.prev_hash should be SHA256 of e1's JSON line
    const expectedHash = AuditWriter._computeHash(lines[0]);
    expect(e2.prev_hash).toBe(expectedHash);
  });

  test('verify() confirms valid chain', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp);
    writer.write('e1', { a: 1 });
    writer.write('e2', { b: 2 });
    writer.write('e3', { c: 3 });

    const result = AuditWriter.verify(writer.activePath);
    expect(result.valid).toBe(true);
    expect(result.totalEntries).toBe(3);
    expect(result.filesVerified).toBe(1);
    expect(result.legacyEntries).toBe(0);
  });

  test('verify() detects tampered entry', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp);
    writer.write('e1', { a: 1 });
    writer.write('e2', { b: 2 });
    writer.write('e3', { c: 3 });

    // Tamper with the second line
    const content = fs.readFileSync(writer.activePath, 'utf-8');
    const lines = content.split('\n');
    const e2 = JSON.parse(lines[1]);
    e2.data.b = 999;
    lines[1] = JSON.stringify(e2);
    fs.writeFileSync(writer.activePath, lines.join('\n'), 'utf-8');

    const result = AuditWriter.verify(writer.activePath);
    expect(result.valid).toBe(false);
    expect(result.chainBreakAt).toBeDefined();
  });

  test('hash chain disabled when hashChain=false', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp, { hashChain: false });
    writer.write('e1', {});

    const entry = JSON.parse(fs.readFileSync(writer.activePath, 'utf-8').trim());
    expect(entry.prev_hash).toBeUndefined();
  });

  test('deterministic serialization produces same hash across calls', () => {
    const data = { v: 1, seq: 0, timestamp: '2026-03-21T00:00:00.000Z', event: 'test', prev_hash: GENESIS_HASH, session_id: null, data: { x: 1 }, adapter: null };
    const json1 = canonicalStringify(data);
    const json2 = canonicalStringify(data);
    expect(json1).toBe(json2);
    expect(AuditWriter._computeHash(json1)).toBe(AuditWriter._computeHash(json2));
  });
});

// ============================================================================
// Recovery (restart, existing files)
// ============================================================================

describe('AuditWriter — Recovery', () => {
  let dir: string;

  beforeEach(() => { dir = tmpDir(); });
  afterEach(() => { fs.rmSync(dir, { recursive: true, force: true }); });

  test('recovers seq and prev_hash from existing file', () => {
    const mp = memoryPath(dir);

    // Write 3 entries with first writer
    const writer1 = new AuditWriter(mp);
    writer1.write('e1', {});
    writer1.write('e2', {});
    writer1.write('e3', {});

    // Create new writer (simulating restart)
    const writer2 = new AuditWriter(mp);
    writer2.write('e4', {});

    // Should continue the chain
    const result = AuditWriter.verify(writer2.activePath);
    expect(result.valid).toBe(true);
    expect(result.totalEntries).toBe(4);

    // e4 should have seq=3
    const lines = fs.readFileSync(writer2.activePath, 'utf-8').trim().split('\n');
    expect(JSON.parse(lines[3]).seq).toBe(3);
  });

  test('handles empty existing active file', () => {
    const mp = memoryPath(dir);
    const activePath = AuditWriter._deriveActivePath(mp);
    fs.writeFileSync(activePath, '', 'utf-8');

    const writer = new AuditWriter(mp);
    writer.write('e1', {});

    const entry = JSON.parse(fs.readFileSync(activePath, 'utf-8').trim());
    expect(entry.seq).toBe(0);
    expect(entry.prev_hash).toBe(GENESIS_HASH);
  });
});

// ============================================================================
// Legacy Compatibility
// ============================================================================

describe('AuditWriter — Legacy', () => {
  let dir: string;

  beforeEach(() => { dir = tmpDir(); });
  afterEach(() => { fs.rmSync(dir, { recursive: true, force: true }); });

  test('verify handles legacy entries (no prev_hash)', () => {
    const mp = memoryPath(dir);
    const activePath = AuditWriter._deriveActivePath(mp);

    // Write legacy-format entries (no v, seq, prev_hash)
    const legacy = [
      JSON.stringify({ timestamp: '2026-01-01T00:00:00Z', event: 'prune', nodes: [], reason: 'test' }),
      JSON.stringify({ timestamp: '2026-01-02T00:00:00Z', event: 'prune', nodes: [], reason: 'test2' }),
    ];
    fs.writeFileSync(activePath, legacy.join('\n') + '\n', 'utf-8');

    const result = AuditWriter.verify(activePath);
    expect(result.valid).toBe(true);
    expect(result.legacyEntries).toBe(2);
    expect(result.totalEntries).toBe(2);
  });

  test('new entries after legacy use LEGACY_BRIDGE sentinel', () => {
    const mp = memoryPath(dir);
    const activePath = AuditWriter._deriveActivePath(mp);

    // Write legacy entry
    fs.writeFileSync(activePath,
      JSON.stringify({ timestamp: '2026-01-01T00:00:00Z', event: 'prune', reason: 'old' }) + '\n',
      'utf-8'
    );

    // New writer appends with hash chain
    const writer = new AuditWriter(mp);
    writer.write('new_event', { x: 1 });

    const lines = fs.readFileSync(activePath, 'utf-8').trim().split('\n');
    expect(lines).toHaveLength(2);
    const newEntry = JSON.parse(lines[1]);
    expect(newEntry.prev_hash).toBe(LEGACY_BRIDGE_HASH);
  });

  test('recovery after legacy→chained transition preserves chain (not LEGACY_BRIDGE)', () => {
    const mp = memoryPath(dir);
    const activePath = AuditWriter._deriveActivePath(mp);

    // Write legacy entry (no hash chain)
    fs.writeFileSync(activePath,
      JSON.stringify({ timestamp: '2026-01-01T00:00:00Z', event: 'prune', reason: 'old' }) + '\n',
      'utf-8'
    );

    // Writer 1: transition from legacy to chained
    const writer1 = new AuditWriter(mp);
    writer1.write('e1', { x: 1 }); // LEGACY_BRIDGE
    writer1.write('e2', { x: 2 }); // chains from e1

    // Writer 2: restart (simulating process restart)
    // Should chain from e2's hash, NOT reset to LEGACY_BRIDGE
    const writer2 = new AuditWriter(mp);
    writer2.write('e3', { x: 3 });

    // Full chain should be valid
    const result = AuditWriter.verify(activePath);
    expect(result.valid).toBe(true);
    expect(result.totalEntries).toBe(4); // legacy + bridge + chained + post-restart

    // Verify the post-restart entry chains properly (not LEGACY_BRIDGE)
    const lines = fs.readFileSync(activePath, 'utf-8').trim().split('\n');
    const e3 = JSON.parse(lines[3]);
    expect(e3.prev_hash).not.toBe(LEGACY_BRIDGE_HASH);
    expect(e3.prev_hash).toBe(AuditWriter._computeHash(lines[2]));
  });

  test('verify passes mixed legacy + chained entries', () => {
    const mp = memoryPath(dir);
    const activePath = AuditWriter._deriveActivePath(mp);

    // Legacy entry
    fs.writeFileSync(activePath,
      JSON.stringify({ timestamp: '2026-01-01T00:00:00Z', event: 'prune', reason: 'old' }) + '\n',
      'utf-8'
    );

    // Chained entries
    const writer = new AuditWriter(mp);
    writer.write('e1', {});
    writer.write('e2', {});

    const result = AuditWriter.verify(activePath);
    expect(result.valid).toBe(true);
    expect(result.legacyEntries).toBe(1);
    expect(result.totalEntries).toBe(3);
  });
});

// ============================================================================
// Query
// ============================================================================

describe('AuditWriter — Query', () => {
  let dir: string;

  beforeEach(() => { dir = tmpDir(); });
  afterEach(() => { fs.rmSync(dir, { recursive: true, force: true }); });

  test('query by event type', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp);
    writer.write('node_create', { node: { id: 'n1' } });
    writer.write('relationship_create', { rel: { id: 'r1' } });
    writer.write('node_create', { node: { id: 'n2' } });

    const result = AuditWriter.query(writer.activePath, { events: ['node_create'] });
    expect(result.entries).toHaveLength(2);
    expect(result.entries[0].data.node).toEqual({ id: 'n1' });
    expect(result.entries[1].data.node).toEqual({ id: 'n2' });
  });

  test('query by session_id', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp);
    writer.write('e1', {}, 'ses_a');
    writer.write('e2', {}, 'ses_b');
    writer.write('e3', {}, 'ses_a');

    const result = AuditWriter.query(writer.activePath, { sessionId: 'ses_a' });
    expect(result.entries).toHaveLength(2);
  });

  test('query by adapter', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp);
    const crewai = { framework: 'crewai', adapter_class: 'CrewAIStorage', operation: 'save' };
    writer.write('e1', {}, null, crewai);
    writer.write('e2', {}, null, null);
    writer.write('e3', {}, null, crewai);

    const result = AuditWriter.query(writer.activePath, { adapter: 'crewai' });
    expect(result.entries).toHaveLength(2);
  });

  test('query by node_id (recursive search)', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp);
    writer.write('node_create', { node: { id: 'tho_abc' } });
    writer.write('node_create', { node: { id: 'tho_def' } });
    writer.write('relationship_create', { source: 'tho_abc', target: 'tho_def' });

    const result = AuditWriter.query(writer.activePath, { nodeId: 'tho_abc' });
    expect(result.entries).toHaveLength(2); // node_create + relationship
  });

  test('query with limit', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp);
    for (let i = 0; i < 10; i++) {
      writer.write('event', { i });
    }

    const result = AuditWriter.query(writer.activePath, { limit: 3 });
    expect(result.entries).toHaveLength(3);
    expect(result.totalScanned).toBeGreaterThanOrEqual(3);
  });

  test('query with verifyChain', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp);
    writer.write('e1', {});
    writer.write('e2', {});

    const result = AuditWriter.query(writer.activePath, { verifyChain: true });
    expect(result.chainValid).toBe(true);
  });

  test('query returns empty for non-existent file', () => {
    const result = AuditWriter.query('/tmp/nonexistent.audit.jsonl');
    expect(result.entries).toHaveLength(0);
    expect(result.filesSearched).toBe(0);
  });
});

// ============================================================================
// on_event Callback
// ============================================================================

describe('AuditWriter — on_event callback', () => {
  let dir: string;

  beforeEach(() => { dir = tmpDir(); });
  afterEach(() => { fs.rmSync(dir, { recursive: true, force: true }); });

  test('fires for every entry', () => {
    const events: AuditEntry[] = [];
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp, { onEvent: (e) => events.push(e) });

    writer.write('e1', {});
    writer.write('e2', {});
    writer.write('e3', {});

    expect(events).toHaveLength(3);
    expect(events[0].event).toBe('e1');
    expect(events[2].event).toBe('e3');
  });

  test('callback failure does not block audit write', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp, {
      onEvent: () => { throw new Error('callback failed'); },
    });

    // Should not throw
    writer.write('e1', { x: 1 });

    // Entry should still be written to disk
    const content = fs.readFileSync(writer.activePath, 'utf-8').trim();
    expect(JSON.parse(content).event).toBe('e1');
  });
});

// ============================================================================
// Rotation
// ============================================================================

describe('AuditWriter — Rotation', () => {
  let dir: string;

  beforeEach(() => { dir = tmpDir(); });
  afterEach(() => { fs.rmSync(dir, { recursive: true, force: true }); });

  test('size-based rotation creates rotated file', () => {
    const mp = memoryPath(dir);
    // 100 bytes limit
    const writer = new AuditWriter(mp, { rotation: 'size:100B', compression: 'none' });

    // Write enough data to trigger rotation
    writer.write('e1', { data: 'x'.repeat(80) });
    writer.write('e2', { data: 'y'.repeat(80) }); // should trigger rotation

    // Should have manifest
    expect(fs.existsSync(writer.manifestPath)).toBe(true);
    const manifest = JSON.parse(fs.readFileSync(writer.manifestPath, 'utf-8'));
    expect(manifest.files.length).toBeGreaterThanOrEqual(1);
  });

  test('gzip compression on rotation', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp, { rotation: 'size:100B', compression: 'gzip', retentionMonths: null });

    writer.write('e1', { data: 'x'.repeat(80) });
    writer.write('e2', { data: 'y'.repeat(80) });

    const manifest = JSON.parse(fs.readFileSync(writer.manifestPath, 'utf-8'));
    if (manifest.files.length > 0) {
      const rotated = manifest.files[0];
      expect(rotated.filename).toContain('.jsonl.gz');

      // Verify we can decompress it
      const gzPath = path.join(dir, rotated.filename);
      if (fs.existsSync(gzPath)) {
        const decompressed = zlib.gunzipSync(fs.readFileSync(gzPath)).toString('utf-8');
        expect(decompressed.trim().length).toBeGreaterThan(0);
      }
    }
  });

  test('cross-file chain continuity after rotation', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp, { rotation: 'size:100B', compression: 'none', retentionMonths: null });

    // Write enough to trigger at least one rotation
    for (let i = 0; i < 5; i++) {
      writer.write(`e${i}`, { data: 'x'.repeat(80) });
    }

    // Verify full chain across all files
    const result = AuditWriter.verify(writer.activePath);
    // (chain break will cause assertion failure below)
    expect(result.valid).toBe(true);
    expect(result.totalEntries).toBe(5);
  });

  test('query across rotated + active files', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp, { rotation: 'size:100B', compression: 'none', retentionMonths: null });

    for (let i = 0; i < 5; i++) {
      writer.write('event', { i, data: 'x'.repeat(80) });
    }

    const result = AuditWriter.query(writer.activePath, { events: ['event'] });
    expect(result.entries).toHaveLength(5);
  });

  test('manifest tracks all rotated files', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp, { rotation: 'size:100B', compression: 'none', retentionMonths: null });

    for (let i = 0; i < 10; i++) {
      writer.write('event', { data: 'x'.repeat(80) });
    }

    const manifest = JSON.parse(fs.readFileSync(writer.manifestPath, 'utf-8'));
    // Should have at least a few rotated files
    expect(manifest.files.length).toBeGreaterThanOrEqual(1);
    for (const f of manifest.files) {
      expect(f.filename).toBeDefined();
      expect(f.entries).toBeGreaterThan(0);
      expect(f.sha256_file).toContain('sha256:');
    }
  });
});

// ============================================================================
// Retention Cleanup
// ============================================================================

describe('AuditWriter — Retention', () => {
  let dir: string;

  beforeEach(() => { dir = tmpDir(); });
  afterEach(() => { fs.rmSync(dir, { recursive: true, force: true }); });

  test('retentionMonths=null keeps all files', () => {
    const mp = memoryPath(dir);
    const writer = new AuditWriter(mp, { retentionMonths: null, rotation: 'size:100B', compression: 'none' });

    for (let i = 0; i < 5; i++) {
      writer.write('event', { data: 'x'.repeat(80) });
    }

    const manifest = JSON.parse(fs.readFileSync(writer.manifestPath, 'utf-8'));
    // All files should be kept
    for (const f of manifest.files) {
      const fp = path.join(dir, f.filename);
      expect(fs.existsSync(fp)).toBe(true);
    }
  });
});

// ============================================================================
// Memory Integration
// ============================================================================

describe('Memory — Audit Trail Integration', () => {
  let dir: string;

  beforeEach(() => { dir = tmpDir(); });
  afterEach(() => { fs.rmSync(dir, { recursive: true, force: true }); });

  test('node_create events are audited', () => {
    const mp = memoryPath(dir);
    const mem = Memory.loadOrCreate(mp, { audit: {} });
    mem.thought('Test thought');
    mem.save();

    const result = Memory.queryAudit(mp, { events: ['node_create'] });
    expect(result.entries.length).toBeGreaterThanOrEqual(1);
    expect(result.entries[0].data.node_id).toBeDefined();
    expect(result.entries[0].data.content).toBe('Test thought');
  });

  test('relationship_create events are audited', () => {
    const mp = memoryPath(dir);
    const mem = Memory.loadOrCreate(mp, { audit: {} });
    const a = mem.thought('A');
    const b = mem.thought('B');
    a.causes(b);
    mem.save();

    const result = Memory.queryAudit(mp, { events: ['relationship_create'] });
    expect(result.entries.length).toBeGreaterThanOrEqual(1);
  });

  test('state_change events are audited', () => {
    const mp = memoryPath(dir);
    const mem = Memory.loadOrCreate(mp, { audit: {} });
    const t = mem.thought('Architecture decision');
    t.decide({ rationale: 'Best approach' });
    mem.save();

    const result = Memory.queryAudit(mp, { events: ['state_change'] });
    expect(result.entries.length).toBeGreaterThanOrEqual(1);
    expect(result.entries[0].data.state_type).toBe('decided');
  });

  test('session_start event is audited', () => {
    const mp = memoryPath(dir);
    const mem = Memory.loadOrCreate(mp, { audit: {} });
    mem.thought('Something');
    mem.sessionStart();
    mem.save();

    const result = Memory.queryAudit(mp, { events: ['session_start'] });
    expect(result.entries.length).toBeGreaterThanOrEqual(1);
    expect(result.entries[0].data.session_id).toBeDefined();
  });

  test('session_end event is audited', () => {
    const mp = memoryPath(dir);
    const mem = Memory.loadOrCreate(mp, { audit: {} });
    mem.thought('Something');
    mem.sessionStart();
    mem.sessionEnd();

    const result = Memory.queryAudit(mp, { events: ['session_end'] });
    expect(result.entries.length).toBeGreaterThanOrEqual(1);
  });

  test('session_wrap event is audited', () => {
    const mp = memoryPath(dir);
    const mem = Memory.loadOrCreate(mp, { audit: {} });
    mem.thought('Something');
    mem.sessionStart();
    mem.sessionWrap();

    const result = Memory.queryAudit(mp, { events: ['session_wrap'] });
    expect(result.entries.length).toBeGreaterThanOrEqual(1);
  });

  test('prune event is audited with hash chain', () => {
    const mp = memoryPath(dir);
    const mem = Memory.loadOrCreate(mp, {
      audit: {},
      temporal: {
        dormancy: { resting: '0s', dormant: '0s', archive: '0s' }
      }
    });

    // Create a node that will be dormant immediately
    mem.thought('Old thought');

    // Manually age the temporal metadata
    const nodeId = mem.thought('Old thought').id;
    const meta = mem.getTemporalMeta(nodeId);
    if (meta) {
      meta.lastTouched = new Date(Date.now() - 86400000 * 30).toISOString();
    }

    mem.prune();

    const result = Memory.queryAudit(mp, { events: ['prune'] });
    expect(result.entries.length).toBeGreaterThanOrEqual(1);
    expect(result.entries[0].data.reason).toContain('pruned');
  });

  test('graduation event is audited', () => {
    const mp = memoryPath(dir);
    const mem = Memory.loadOrCreate(mp, {
      audit: {},
      temporal: {
        tiers: {
          developing: { maxAge: '7d', graduationThreshold: 2 },
        }
      }
    });

    // Create a node and touch it enough to graduate
    const t = mem.thought('Will graduate');
    // Touch to increment frequency (creation = 1, explicit touch = 2)
    mem.touchNodes([t.id]);

    const result = Memory.queryAudit(mp, { events: ['graduation'] });
    expect(result.entries.length).toBeGreaterThanOrEqual(1);
    expect(result.entries[0].data.old_tier).toBe('current');
    expect(result.entries[0].data.new_tier).toBe('developing');
  });

  test('verifyAudit confirms chain integrity', () => {
    const mp = memoryPath(dir);
    const mem = Memory.loadOrCreate(mp, { audit: {} });
    mem.thought('A');
    mem.thought('B');
    mem.thought('C');
    mem.save();

    const result = Memory.verifyAudit(mp);
    expect(result.valid).toBe(true);
    expect(result.totalEntries).toBeGreaterThanOrEqual(3);
  });

  test('setAdapterContext flows through to audit entries', () => {
    const mp = memoryPath(dir);
    const mem = Memory.loadOrCreate(mp, { audit: {} });
    mem.setAdapterContext('langgraph', 'LangGraphStore', 'put');
    mem.thought('From LangGraph');
    mem.clearAdapterContext();
    mem.save();

    const result = Memory.queryAudit(mp, { adapter: 'langgraph' });
    expect(result.entries.length).toBeGreaterThanOrEqual(1);
    expect(result.entries[0].adapter!.framework).toBe('langgraph');
  });

  test('on_event callback fires for Memory operations', () => {
    const events: AuditEntry[] = [];
    const mp = memoryPath(dir);
    const mem = Memory.loadOrCreate(mp, {
      audit: { onEvent: (e) => events.push(e) },
    });

    mem.thought('Test');
    expect(events.length).toBeGreaterThanOrEqual(1);
    expect(events[0].event).toBe('node_create');
  });

  test('no audit when no audit config', () => {
    const mp = memoryPath(dir);
    const mem = Memory.loadOrCreate(mp); // no audit config

    mem.thought('No audit');
    mem.save();

    // Should not create hash-chained audit file
    // (legacy audit only on prune)
    const auditPath = AuditWriter._deriveActivePath(mp);
    // No audit file should be created for non-prune operations without audit config
    if (fs.existsSync(auditPath)) {
      const content = fs.readFileSync(auditPath, 'utf-8').trim();
      // If it exists, it should have no hash-chained entries
      if (content) {
        const entry = JSON.parse(content.split('\n')[0]);
        // Legacy entries don't have 'v' field
        expect(entry.v).toBeUndefined();
      }
    }
  });

  test('audit survives save/reload cycle', () => {
    const mp = memoryPath(dir);

    // Session 1: create nodes
    const mem1 = Memory.loadOrCreate(mp, { audit: {} });
    mem1.thought('Session 1 thought');
    mem1.save();

    // Session 2: create more nodes
    const mem2 = Memory.loadOrCreate(mp, { audit: {} });
    mem2.thought('Session 2 thought');
    mem2.save();

    // Chain should be valid across both sessions
    const result = Memory.verifyAudit(mp);
    expect(result.valid).toBe(true);
    expect(result.totalEntries).toBeGreaterThanOrEqual(2);
  });

  test('full lifecycle: create → add → session → wrap → verify → query', () => {
    const mp = memoryPath(dir);
    const mem = Memory.loadOrCreate(mp, { audit: {} });

    // Build reasoning graph
    const q = mem.question('Which framework?');
    const a = mem.alternative(q, 'React');
    const b = mem.alternative(q, 'Vue');
    mem.tension(a, b, 'ecosystem vs simplicity');
    a.decide({ rationale: 'Larger ecosystem' });

    // Session lifecycle
    mem.sessionStart();
    mem.sessionWrap();

    // Verify chain
    const verifyResult = Memory.verifyAudit(mp);
    expect(verifyResult.valid).toBe(true);

    // Query node creation events
    const createEvents = Memory.queryAudit(mp, { events: ['node_create'] });
    expect(createEvents.entries.length).toBeGreaterThanOrEqual(3); // question + 2 alternatives

    // Query relationship events
    const relEvents = Memory.queryAudit(mp, { events: ['relationship_create'] });
    expect(relEvents.entries.length).toBeGreaterThanOrEqual(1);

    // Query state changes
    const stateEvents = Memory.queryAudit(mp, { events: ['state_change'] });
    expect(stateEvents.entries.length).toBeGreaterThanOrEqual(1);

    // Query session events
    const sessionEvents = Memory.queryAudit(mp, { events: ['session_start', 'session_end', 'session_wrap'] });
    expect(sessionEvents.entries.length).toBeGreaterThanOrEqual(2); // start + end (from wrap) + wrap
  });

  test('queryAudit accepts memory file path (derives audit path)', () => {
    const mp = memoryPath(dir);
    const mem = Memory.loadOrCreate(mp, { audit: {} });
    mem.thought('Test');
    mem.save();

    // Pass the .json path — should derive .audit.jsonl automatically
    const result = Memory.queryAudit(mp);
    expect(result.entries.length).toBeGreaterThanOrEqual(1);
  });

  test('verifyAudit accepts memory file path', () => {
    const mp = memoryPath(dir);
    const mem = Memory.loadOrCreate(mp, { audit: {} });
    mem.thought('Test');
    mem.save();

    const result = Memory.verifyAudit(mp);
    expect(result.valid).toBe(true);
  });

  test('snapshot event is audited', () => {
    const mp = memoryPath(dir);
    const mem = Memory.loadOrCreate(mp, { audit: {} });
    mem.thought('Something to snapshot');
    mem.snapshot('test-checkpoint');
    mem.save();

    const result = Memory.queryAudit(mp, { events: ['snapshot'] });
    expect(result.entries.length).toBeGreaterThanOrEqual(1);
    expect(result.entries[0].data.snapshot_name).toBe('test-checkpoint');
    expect(result.entries[0].data.node_count).toBe(1);
  });

  test('restore event is audited (write-first)', () => {
    const mp = memoryPath(dir);
    const mem = Memory.loadOrCreate(mp, { audit: {}, autoSnapshot: false });
    mem.thought('Before snapshot');
    const snapId = mem.snapshot('restore-test');
    mem.thought('After snapshot');
    mem.restore(snapId);
    mem.save();

    const result = Memory.queryAudit(mp, { events: ['restore'] });
    expect(result.entries.length).toBeGreaterThanOrEqual(1);
    expect(result.entries[0].data.snapshot_id).toBe(snapId);
    expect(result.entries[0].data.nodes_before).toBe(2); // both thoughts
    expect(result.entries[0].data.nodes_after).toBe(1);  // only the first
  });

  test('removeStates event is audited (write-first)', () => {
    const mp = memoryPath(dir);
    const mem = Memory.loadOrCreate(mp, { audit: {} });
    const t = mem.thought('Architecture choice');
    t.decide({ rationale: 'Best option' });

    // Remove the decided state
    mem.removeStates(t.id, 'decided');
    mem.save();

    const result = Memory.queryAudit(mp, { events: ['state_change'] });
    // Should have: state_change (add) + state_change (remove)
    const removeEvents = result.entries.filter(e => e.data.action === 'remove');
    expect(removeEvents.length).toBeGreaterThanOrEqual(1);
    expect(removeEvents[0].data.node_id).toBe(t.id);
  });

  test('modifier_add event is audited', () => {
    const mp = memoryPath(dir);
    const mem = Memory.loadOrCreate(mp, { audit: {} });
    const t = mem.thought('Important finding');
    t.urgent();
    mem.save();

    const result = Memory.queryAudit(mp, { events: ['modifier_add'] });
    expect(result.entries.length).toBeGreaterThanOrEqual(1);
    expect(result.entries[0].data.node_id).toBe(t.id);
    expect(result.entries[0].data.modifier).toBe('urgent');
  });

  test('budget_apply event is audited when nodes are excluded', () => {
    const mp = memoryPath(dir);
    const mem = Memory.loadOrCreate(mp, { audit: {} });

    // Create enough nodes that a tight budget will exclude some
    for (let i = 0; i < 10; i++) {
      mem.thought(`Thought number ${i} with enough content to matter`);
    }

    // Serialize with a very small token budget (should exclude most nodes)
    mem.toFlowScript({ maxTokens: 50 });
    mem.save();

    const result = Memory.queryAudit(mp, { events: ['budget_apply'] });
    expect(result.entries.length).toBeGreaterThanOrEqual(1);
    expect(result.entries[0].data.nodes_before).toBe(10);
    expect((result.entries[0].data.nodes_after as number)).toBeLessThan(10);
  });
});
